[profile.default]
optimizer = true
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
polygonMumbai = "${MUMBAI_RPC}"
bscTestnet = "${BSC_RPC}"
goerli = "${GOERLI_RPC}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config